server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_keskonavu
    username: postgres
    password: mdpadmin
  application:
    name: '@project.name@'
  jta:
    enabled: false
  jpa:
    show-sql: true
    open-in-view: false
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  cache:
    jcache:
      config: classpath:cache/ehcache.xml
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    fr.epita.kesKonAVu: INFO